
 
import {Scene} from "phaser";
    
            const _TiedVineStrawberry = require( './sprites/TiedVineStrawberry/TiedVineStrawberry')
const _TiedVineSaltedcola = require( './sprites/TiedVineSaltedcola/TiedVineSaltedcola')
const _TiedVinePepelepsi = require( './sprites/TiedVinePepelepsi/TiedVinePepelepsi')
const _TiedVineMilk = require( './sprites/TiedVineMilk/TiedVineMilk')
const _TiedVine7Hp = require( './sprites/TiedVine7Hp/TiedVine7Hp')
const _TiedVine = require( './sprites/TiedVine/TiedVine')
const _Flora = require( './sprites/Flora/Flora')
const _FloraUndies = require( './sprites/FloraUndies/FloraUndies')
const _FloraLeftboobVineUrine = require( './sprites/FloraLeftboobVineUrine/FloraLeftboobVineUrine')
const _FloraLeftboobVineStrawberry = require( './sprites/FloraLeftboobVineStrawberry/FloraLeftboobVineStrawberry')
const _FloraLeftboobVineSaltedcola = require( './sprites/FloraLeftboobVineSaltedcola/FloraLeftboobVineSaltedcola')
const _FloraLeftboobVinePepelepsi = require( './sprites/FloraLeftboobVinePepelepsi/FloraLeftboobVinePepelepsi')
const _FloraLeftboobVineMilk = require( './sprites/FloraLeftboobVineMilk/FloraLeftboobVineMilk')
const _FloraLeftboobVine7Hp = require( './sprites/FloraLeftboobVine7Hp/FloraLeftboobVine7Hp')
const _FloraLeftboobVine = require( './sprites/FloraLeftboobVine/FloraLeftboobVine')
const _SquashedVineUrine = require( './sprites/SquashedVineUrine/SquashedVineUrine')
const _SquashedVineStrawberry = require( './sprites/SquashedVineStrawberry/SquashedVineStrawberry')
const _SquashedVineSaltedcola = require( './sprites/SquashedVineSaltedcola/SquashedVineSaltedcola')
const _SquashedVinePepelepsi = require( './sprites/SquashedVinePepelepsi/SquashedVinePepelepsi')
const _SquashedVineMilk = require( './sprites/SquashedVineMilk/SquashedVineMilk')
const _SquashedVine7Hp = require( './sprites/SquashedVine7Hp/SquashedVine7Hp')
const _SquashedVine = require( './sprites/SquashedVine/SquashedVine')
const _FloraTorsoVineUrine = require( './sprites/FloraTorsoVineUrine/FloraTorsoVineUrine')
const _FloraTorsoVineStrawberry = require( './sprites/FloraTorsoVineStrawberry/FloraTorsoVineStrawberry')
const _FloraTorsoVineSaltedcola = require( './sprites/FloraTorsoVineSaltedcola/FloraTorsoVineSaltedcola')
const _FloraTorsoVinePepelepsi = require( './sprites/FloraTorsoVinePepelepsi/FloraTorsoVinePepelepsi')
const _FloraTorsoVineMilk = require( './sprites/FloraTorsoVineMilk/FloraTorsoVineMilk')
const _FloraTorsoVine7Hp = require( './sprites/FloraTorsoVine7Hp/FloraTorsoVine7Hp')
const _FloraTorsoVine = require( './sprites/FloraTorsoVine/FloraTorsoVine')
const _WateredVineUrine = require( './sprites/WateredVineUrine/WateredVineUrine')
const _WateredVineStrawberry = require( './sprites/WateredVineStrawberry/WateredVineStrawberry')
const _WateredVineSaltedcola = require( './sprites/WateredVineSaltedcola/WateredVineSaltedcola')
const _WateredVinePepelepsi = require( './sprites/WateredVinePepelepsi/WateredVinePepelepsi')
const _WateredVineMilk = require( './sprites/WateredVineMilk/WateredVineMilk')
const _WateredVine7Hp = require( './sprites/WateredVine7Hp/WateredVine7Hp')
const _WateredVine = require( './sprites/WateredVine/WateredVine')
const _TiedVineUrine = require( './sprites/TiedVineUrine/TiedVineUrine')
const _Tictactoe = require( './sprites/Tictactoe/Tictactoe')
const _StabbedVineUrine = require( './sprites/StabbedVineUrine/StabbedVineUrine')
const _StabbedVineStrawberry = require( './sprites/StabbedVineStrawberry/StabbedVineStrawberry')
const _StabbedVineSaltedcola = require( './sprites/StabbedVineSaltedcola/StabbedVineSaltedcola')
const _StabbedVinePepelepsi = require( './sprites/StabbedVinePepelepsi/StabbedVinePepelepsi')
const _StabbedVineMilk = require( './sprites/StabbedVineMilk/StabbedVineMilk')
const _StabbedVine7Hp = require( './sprites/StabbedVine7Hp/StabbedVine7Hp')
const _StabbedVine = require( './sprites/StabbedVine/StabbedVine')
const _FloraRightarmVineUrine = require( './sprites/FloraRightarmVineUrine/FloraRightarmVineUrine')
const _FloraRightarmVineStrawberry = require( './sprites/FloraRightarmVineStrawberry/FloraRightarmVineStrawberry')
const _FloraRightarmVineSaltedcola = require( './sprites/FloraRightarmVineSaltedcola/FloraRightarmVineSaltedcola')
const _FloraRightarmVinePepelepsi = require( './sprites/FloraRightarmVinePepelepsi/FloraRightarmVinePepelepsi')
const _FloraRightarmVineMilk = require( './sprites/FloraRightarmVineMilk/FloraRightarmVineMilk')
const _FloraRightarmVine7Hp = require( './sprites/FloraRightarmVine7Hp/FloraRightarmVine7Hp')
const _FloraRightarmVine = require( './sprites/FloraRightarmVine/FloraRightarmVine')
const _FloraRightboobVineUrine = require( './sprites/FloraRightboobVineUrine/FloraRightboobVineUrine')
const _FloraRightboobVineStrawberry = require( './sprites/FloraRightboobVineStrawberry/FloraRightboobVineStrawberry')
const _FloraRightboobVineSaltedcola = require( './sprites/FloraRightboobVineSaltedcola/FloraRightboobVineSaltedcola')
const _FloraRightboobVinePepelepsi = require( './sprites/FloraRightboobVinePepelepsi/FloraRightboobVinePepelepsi')
const _FloraRightboobVineMilk = require( './sprites/FloraRightboobVineMilk/FloraRightboobVineMilk')
const _FloraRightboobVine7Hp = require( './sprites/FloraRightboobVine7Hp/FloraRightboobVine7Hp')
const _FloraRightboobVine = require( './sprites/FloraRightboobVine/FloraRightboobVine')
const _SleepvineUrinePng = require( './sprites/SleepvineUrinePng/SleepvineUrinePng')
const _SleepvineStrawberryPng = require( './sprites/SleepvineStrawberryPng/SleepvineStrawberryPng')
const _SleepvineSaltedcolaPng = require( './sprites/SleepvineSaltedcolaPng/SleepvineSaltedcolaPng')
const _SleepvinePepelepsi = require( './sprites/SleepvinePepelepsi/SleepvinePepelepsi')
const _SleepvineMilk = require( './sprites/SleepvineMilk/SleepvineMilk')
const _Sleepvine7Hp = require( './sprites/Sleepvine7Hp/Sleepvine7Hp')
const _Sleepvine = require( './sprites/Sleepvine/Sleepvine')
const _LaptopVineUrine = require( './sprites/LaptopVineUrine/LaptopVineUrine')
const _LaptopVineStrawberry = require( './sprites/LaptopVineStrawberry/LaptopVineStrawberry')
const _LaptopVineSaltedcola = require( './sprites/LaptopVineSaltedcola/LaptopVineSaltedcola')
const _LaptopVinePepelepsi = require( './sprites/LaptopVinePepelepsi/LaptopVinePepelepsi')
const _LaptopVineMilk = require( './sprites/LaptopVineMilk/LaptopVineMilk')
const _LaptopVine7Hp = require( './sprites/LaptopVine7Hp/LaptopVine7Hp')
const _LaptopVine = require( './sprites/LaptopVine/LaptopVine')
const _Game = require( './sprites/Game/Game')
const _TeddyVineUrine = require( './sprites/TeddyVineUrine/TeddyVineUrine')
const _TeddyVineStrawberry = require( './sprites/TeddyVineStrawberry/TeddyVineStrawberry')
const _TeddyVineSaltedcola = require( './sprites/TeddyVineSaltedcola/TeddyVineSaltedcola')
const _TeddyVinePepelepsi = require( './sprites/TeddyVinePepelepsi/TeddyVinePepelepsi')
const _TeddyVineMilk = require( './sprites/TeddyVineMilk/TeddyVineMilk')
const _TeddyVine7Hp = require( './sprites/TeddyVine7Hp/TeddyVine7Hp')
const _TeddyVine = require( './sprites/TeddyVine/TeddyVine')
const _FloraRightlegVineUrine = require( './sprites/FloraRightlegVineUrine/FloraRightlegVineUrine')
const _FloraRightlegVineStrawberry = require( './sprites/FloraRightlegVineStrawberry/FloraRightlegVineStrawberry')
const _FloraRightlegVineSaltedcola = require( './sprites/FloraRightlegVineSaltedcola/FloraRightlegVineSaltedcola')
const _FloraRightlegVinePepelepsi = require( './sprites/FloraRightlegVinePepelepsi/FloraRightlegVinePepelepsi')
const _FloraRightlegVineMilk = require( './sprites/FloraRightlegVineMilk/FloraRightlegVineMilk')
const _FloraRightlegVine7Hp = require( './sprites/FloraRightlegVine7Hp/FloraRightlegVine7Hp')
const _FloraRightlegVine = require( './sprites/FloraRightlegVine/FloraRightlegVine')
const _PosterVineUrine = require( './sprites/PosterVineUrine/PosterVineUrine')
const _PosterVineStrawberry = require( './sprites/PosterVineStrawberry/PosterVineStrawberry')
const _PosterVineSaltedcola = require( './sprites/PosterVineSaltedcola/PosterVineSaltedcola')
const _PosterVinePepelepsi = require( './sprites/PosterVinePepelepsi/PosterVinePepelepsi')
const _PosterVineMilk = require( './sprites/PosterVineMilk/PosterVineMilk')
const _PosterVine7Hp = require( './sprites/PosterVine7Hp/PosterVine7Hp')
const _PosterVine = require( './sprites/PosterVine/PosterVine')
const _DruggedVineUrine = require( './sprites/DruggedVineUrine/DruggedVineUrine')
const _DruggedVineStrawberry = require( './sprites/DruggedVineStrawberry/DruggedVineStrawberry')
const _DruggedVineSaltedcola = require( './sprites/DruggedVineSaltedcola/DruggedVineSaltedcola')
const _DruggedVinePepelepsi = require( './sprites/DruggedVinePepelepsi/DruggedVinePepelepsi')
const _DruggedVineMilk = require( './sprites/DruggedVineMilk/DruggedVineMilk')
const _DruggedVine7Hp = require( './sprites/DruggedVine7Hp/DruggedVine7Hp')
const _DruggedVine = require( './sprites/DruggedVine/DruggedVine')
const _FloraLeftlegVineUrine = require( './sprites/FloraLeftlegVineUrine/FloraLeftlegVineUrine')
const _FloraLeftlegVineStrawberry = require( './sprites/FloraLeftlegVineStrawberry/FloraLeftlegVineStrawberry')
const _FloraLeftlegVineSaltedcola = require( './sprites/FloraLeftlegVineSaltedcola/FloraLeftlegVineSaltedcola')
const _FloraLeftlegVinePepelepsi = require( './sprites/FloraLeftlegVinePepelepsi/FloraLeftlegVinePepelepsi')
const _FloraLeftlegVineMilk = require( './sprites/FloraLeftlegVineMilk/FloraLeftlegVineMilk')
const _FloraLeftlegVine7Hp = require( './sprites/FloraLeftlegVine7Hp/FloraLeftlegVine7Hp')
const _FloraLeftlegVine = require( './sprites/FloraLeftlegVine/FloraLeftlegVine')
const _FloraLeftarmVineUrine = require( './sprites/FloraLeftarmVineUrine/FloraLeftarmVineUrine')
const _FloraLeftarmVineStrawberry = require( './sprites/FloraLeftarmVineStrawberry/FloraLeftarmVineStrawberry')
const _FloraLeftarmVineSaltedcola = require( './sprites/FloraLeftarmVineSaltedcola/FloraLeftarmVineSaltedcola')
const _FloraLeftarmVinePepelepsi = require( './sprites/FloraLeftarmVinePepelepsi/FloraLeftarmVinePepelepsi')
const _FloraLeftarmVineMilk = require( './sprites/FloraLeftarmVineMilk/FloraLeftarmVineMilk')
const _FloraLeftarmVine7Hp = require( './sprites/FloraLeftarmVine7Hp/FloraLeftarmVine7Hp')
const _FloraLeftarmVine = require( './sprites/FloraLeftarmVine/FloraLeftarmVine')
const _OpenWindow = require( './sprites/OpenWindow/OpenWindow')
const _DoorvineUrine = require( './sprites/DoorvineUrine/DoorvineUrine')
const _DoorvineStrawberry = require( './sprites/DoorvineStrawberry/DoorvineStrawberry')
const _DoorvineSaltedcola = require( './sprites/DoorvineSaltedcola/DoorvineSaltedcola')
const _DoorvinePepelepsi = require( './sprites/DoorvinePepelepsi/DoorvinePepelepsi')
const _DoorvineMilk = require( './sprites/DoorvineMilk/DoorvineMilk')
const _Doorvine7Hp = require( './sprites/Doorvine7Hp/Doorvine7Hp')
const _Doorvine = require( './sprites/Doorvine/Doorvine')
const _Midtree = require( './sprites/Midtree/Midtree')
const _FloraPussyVineStrawberry = require( './sprites/FloraPussyVineStrawberry/FloraPussyVineStrawberry')
const _FloraPussyVinePepelepsi = require( './sprites/FloraPussyVinePepelepsi/FloraPussyVinePepelepsi')
const _FloraPussyVineMilk = require( './sprites/FloraPussyVineMilk/FloraPussyVineMilk')
const _FloraPussyVine7Hp = require( './sprites/FloraPussyVine7Hp/FloraPussyVine7Hp')
const _FloraPussySaltedcola = require( './sprites/FloraPussySaltedcola/FloraPussySaltedcola')
const _FloraPussyUrine = require( './sprites/FloraPussyUrine/FloraPussyUrine')
const _FloraPussyVine = require( './sprites/FloraPussyVine/FloraPussyVine')
const _BigtreeUrine = require( './sprites/BigtreeUrine/BigtreeUrine')
const _BigtreeStrawberry = require( './sprites/BigtreeStrawberry/BigtreeStrawberry')
const _BigtreeSaltedcola = require( './sprites/BigtreeSaltedcola/BigtreeSaltedcola')
const _BigtreePepelepsi = require( './sprites/BigtreePepelepsi/BigtreePepelepsi')
const _BigtreeMilk = require( './sprites/BigtreeMilk/BigtreeMilk')
const _Bigtree7Hp = require( './sprites/Bigtree7Hp/Bigtree7Hp')
const _Bigtree = require( './sprites/Bigtree/Bigtree')
const _FloraMouthVineUrine = require( './sprites/FloraMouthVineUrine/FloraMouthVineUrine')
const _FloraMouthVineStrawberry = require( './sprites/FloraMouthVineStrawberry/FloraMouthVineStrawberry')
const _FloraMouthVineSaltedcola = require( './sprites/FloraMouthVineSaltedcola/FloraMouthVineSaltedcola')
const _FloraMouthVinePepelepsi = require( './sprites/FloraMouthVinePepelepsi/FloraMouthVinePepelepsi')
const _FloraMouthVineMilk = require( './sprites/FloraMouthVineMilk/FloraMouthVineMilk')
const _FloraMouthVine7Hp = require( './sprites/FloraMouthVine7Hp/FloraMouthVine7Hp')
const _FloraMouthVine = require( './sprites/FloraMouthVine/FloraMouthVine')
const _Book = require( './sprites/Book/Book')
const _Bookclutter = require( './sprites/Bookclutter/Bookclutter')
const _BookvineUrine = require( './sprites/BookvineUrine/BookvineUrine')
const _BookvineStrawberry = require( './sprites/BookvineStrawberry/BookvineStrawberry')
const _BookvineSaltedcola = require( './sprites/BookvineSaltedcola/BookvineSaltedcola')
const _BookvinePepelepsi = require( './sprites/BookvinePepelepsi/BookvinePepelepsi')
const _BookvineMilk = require( './sprites/BookvineMilk/BookvineMilk')
const _Bookvine7Hp = require( './sprites/Bookvine7Hp/Bookvine7Hp')
const _Bookvine = require( './sprites/Bookvine/Bookvine')
const _Puddle = require( './sprites/Puddle/Puddle')
const _FloraAssVineUrine = require( './sprites/FloraAssVineUrine/FloraAssVineUrine')
const _FloraAssVineStrawberry = require( './sprites/FloraAssVineStrawberry/FloraAssVineStrawberry')
const _FloraAssVineSaltedcola = require( './sprites/FloraAssVineSaltedcola/FloraAssVineSaltedcola')
const _FloraAssVinePepelepsi = require( './sprites/FloraAssVinePepelepsi/FloraAssVinePepelepsi')
const _FloraAssVineMilk = require( './sprites/FloraAssVineMilk/FloraAssVineMilk')
const _FloraAssVine7Hp = require( './sprites/FloraAssVine7Hp/FloraAssVine7Hp')
const _FloraAssVine = require( './sprites/FloraAssVine/FloraAssVine')
const _FloraDown = require( './sprites/FloraDown/FloraDown')
const _FlorasadDown = require( './sprites/FlorasadDown/FlorasadDown')
const _Cum = require( './sprites/Cum/Cum')
            const SpriteNames = [_TiedVineStrawberry,_TiedVineSaltedcola,_TiedVinePepelepsi,_TiedVineMilk,_TiedVine7Hp,_TiedVine,_Flora,_FloraUndies,_FloraLeftboobVineUrine,_FloraLeftboobVineStrawberry,_FloraLeftboobVineSaltedcola,_FloraLeftboobVinePepelepsi,_FloraLeftboobVineMilk,_FloraLeftboobVine7Hp,_FloraLeftboobVine,_SquashedVineUrine,_SquashedVineStrawberry,_SquashedVineSaltedcola,_SquashedVinePepelepsi,_SquashedVineMilk,_SquashedVine7Hp,_SquashedVine,_FloraTorsoVineUrine,_FloraTorsoVineStrawberry,_FloraTorsoVineSaltedcola,_FloraTorsoVinePepelepsi,_FloraTorsoVineMilk,_FloraTorsoVine7Hp,_FloraTorsoVine,_WateredVineUrine,_WateredVineStrawberry,_WateredVineSaltedcola,_WateredVinePepelepsi,_WateredVineMilk,_WateredVine7Hp,_WateredVine,_TiedVineUrine,_Tictactoe,_StabbedVineUrine,_StabbedVineStrawberry,_StabbedVineSaltedcola,_StabbedVinePepelepsi,_StabbedVineMilk,_StabbedVine7Hp,_StabbedVine,_FloraRightarmVineUrine,_FloraRightarmVineStrawberry,_FloraRightarmVineSaltedcola,_FloraRightarmVinePepelepsi,_FloraRightarmVineMilk,_FloraRightarmVine7Hp,_FloraRightarmVine,_FloraRightboobVineUrine,_FloraRightboobVineStrawberry,_FloraRightboobVineSaltedcola,_FloraRightboobVinePepelepsi,_FloraRightboobVineMilk,_FloraRightboobVine7Hp,_FloraRightboobVine,_SleepvineUrinePng,_SleepvineStrawberryPng,_SleepvineSaltedcolaPng,_SleepvinePepelepsi,_SleepvineMilk,_Sleepvine7Hp,_Sleepvine,_LaptopVineUrine,_LaptopVineStrawberry,_LaptopVineSaltedcola,_LaptopVinePepelepsi,_LaptopVineMilk,_LaptopVine7Hp,_LaptopVine,_Game,_TeddyVineUrine,_TeddyVineStrawberry,_TeddyVineSaltedcola,_TeddyVinePepelepsi,_TeddyVineMilk,_TeddyVine7Hp,_TeddyVine,_FloraRightlegVineUrine,_FloraRightlegVineStrawberry,_FloraRightlegVineSaltedcola,_FloraRightlegVinePepelepsi,_FloraRightlegVineMilk,_FloraRightlegVine7Hp,_FloraRightlegVine,_PosterVineUrine,_PosterVineStrawberry,_PosterVineSaltedcola,_PosterVinePepelepsi,_PosterVineMilk,_PosterVine7Hp,_PosterVine,_DruggedVineUrine,_DruggedVineStrawberry,_DruggedVineSaltedcola,_DruggedVinePepelepsi,_DruggedVineMilk,_DruggedVine7Hp,_DruggedVine,_FloraLeftlegVineUrine,_FloraLeftlegVineStrawberry,_FloraLeftlegVineSaltedcola,_FloraLeftlegVinePepelepsi,_FloraLeftlegVineMilk,_FloraLeftlegVine7Hp,_FloraLeftlegVine,_FloraLeftarmVineUrine,_FloraLeftarmVineStrawberry,_FloraLeftarmVineSaltedcola,_FloraLeftarmVinePepelepsi,_FloraLeftarmVineMilk,_FloraLeftarmVine7Hp,_FloraLeftarmVine,_OpenWindow,_DoorvineUrine,_DoorvineStrawberry,_DoorvineSaltedcola,_DoorvinePepelepsi,_DoorvineMilk,_Doorvine7Hp,_Doorvine,_Midtree,_FloraPussyVineStrawberry,_FloraPussyVinePepelepsi,_FloraPussyVineMilk,_FloraPussyVine7Hp,_FloraPussySaltedcola,_FloraPussyUrine,_FloraPussyVine,_BigtreeUrine,_BigtreeStrawberry,_BigtreeSaltedcola,_BigtreePepelepsi,_BigtreeMilk,_Bigtree7Hp,_Bigtree,_FloraMouthVineUrine,_FloraMouthVineStrawberry,_FloraMouthVineSaltedcola,_FloraMouthVinePepelepsi,_FloraMouthVineMilk,_FloraMouthVine7Hp,_FloraMouthVine,_Book,_Bookclutter,_BookvineUrine,_BookvineStrawberry,_BookvineSaltedcola,_BookvinePepelepsi,_BookvineMilk,_Bookvine7Hp,_Bookvine,_Puddle,_FloraAssVineUrine,_FloraAssVineStrawberry,_FloraAssVineSaltedcola,_FloraAssVinePepelepsi,_FloraAssVineMilk,_FloraAssVine7Hp,_FloraAssVine,_FloraDown,_FlorasadDown,_Cum]
            export default class PreloadVines extends Scene{
        
            constructor(){
                super('preload_Vines')  
               
            }
            preload() {
            
           
                for(const sprite_set of SpriteNames){
                    for(const sprite_name of sprite_set.default){
                        this.load.image(  sprite_name[0],  sprite_name[1]);
                    }
                }
            }

   
                create() {
            this.scene.start('Vines')
        }

    }